"""Initial migration

Revision ID: ab6544076cfa
Revises: 
Create Date: 2026-06-17 06:17:43.203367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6544076cfa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_machines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('initial_state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('state_machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_state_machines_name'), ['name'], unique=True)

    op.create_table('simulation_histories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['state_machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_terminal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['state_machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('from_state', sa.String(), nullable=False),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['state_machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transitions')
    op.drop_table('states')
    op.drop_table('simulation_histories')
    with op.batch_alter_table('state_machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_machines_name'))

    op.drop_table('state_machines')
    # ### end Alembic commands ###
